### ISSUE TITLE
download_available option fails with `unexpected keyword argument 'status'`

### ISSUE THREAD

**Issue by willmacs** [eodms-sgdot/eodms-cli#19]
### IMPACT
Users cannot download fulfilled orders as intended.
### ERROR
```
->> Please choose the type of process [1]: 4

--------------Enter Output Geospatial File--------------

->> Enter the path of the output geospatial file (can also be GeoJSON, KML, GML or Shapefile) (default is no output file):


Use this command-line syntax to run the same parameters:
python C:\Users\Public\eodms-cli\eodms_cli.py -prc download_available -s

ERROR:
Traceback (most recent call last):
  File "C:\Users\Public\eodms-cli\eodms_cli.py", line 1557, in cli
    prmpt.prompt()
  File "C:\Users\Public\eodms-cli\eodms_cli.py", line 1209, in prompt
    self.eod.download_available(self.params)
  File "C:\Users\Public\eodms-cli\scripts\utils.py", line 1932, in download_available
    orders = self.eodms_rapi.get_orders(max_orders=max_orders,
TypeError: EODMSRAPI.get_orders() got an unexpected keyword argument 'status'


Exiting process.
```

**Comment by willmacs** [comment]
Can we close @keballantyne? If so, can you tag the commit in your close comment?
