### ISSUE TITLE
When using a CSV search results from EODMS GUI, an error occurs when WorldView-3 is in the list

### ISSUE THREAD

**Issue by keballantyne** [eodms-sgdot/eodms-cli#26]
ERROR:

```python
Traceback (most recent call last):
  File "C:\Working\Development\EODMS\eodms-cli\dev\eodms_cli.py", line 1655, in cli
    prmpt.prompt()
  File "C:\Working\Development\EODMS\eodms-cli\dev\eodms_cli.py", line 1246, in prompt
    self.eod.order_csv(self.params)
  File "C:\Working\Development\EODMS\eodms-cli\dev\scripts\utils.py", line 1736, in order_csv
    query_imgs = self._get_eodms_res(csv_fn, max_images)
  File "C:\Working\Development\EODMS\eodms-cli\dev\scripts\utils.py", line 446, in _get_eodms_res
    res = self.eodms_rapi.get_record(coll, rec_id)
  File "C:\Python310\lib\site-packages\eodms_rapi\eodms.py", line 2478, in get_record
    self.collection = self.get_collection_id(collection)
  File "C:\Python310\lib\site-packages\eodms_rapi\eodms.py", line 1576, in get_collection_id
    if coll.lower() == v['title'].lower():
AttributeError: 'list' object has no attribute 'lower'
```

**Comment by keballantyne** [comment]
Fixed in version 3.2.0 https://github.com/eodms-sgdot/eodms-cli/commit/cf7201d4857612d7ccbc8ae9ebd164d9f96d1956
